from pathlib import Path
import hashlib,json
import pandas as pd

ROOT=Path(__file__).resolve().parents[1]; H=ROOT/'reports/sector_strategy/v2/paper_handoff'; OUT=H/'phase13c'; OUT.mkdir(parents=True,exist_ok=True)
EVIDENCE=['historical_target_to_order_parity.csv','historical_risk_parity.csv','phase13b_execution_parity_manifest.json']
hashes={f:hashlib.sha256((H/f).read_bytes()).hexdigest() for f in EVIDENCE}
orders=pd.read_csv(H/'historical_target_to_order_parity.csv'); risk=pd.read_csv(H/'historical_risk_parity.csv'); bad=orders[orders.result.eq('FAIL')].copy()
last=risk.groupby(['rebalance_id','symbol']).tail(1)[['rebalance_id','symbol','requested_quantity','approved_quantity','approved','reason']]
bad=bad.merge(last,on=['rebalance_id','symbol'],how='left'); bad['quantity_difference']=bad.actual_quantity-bad.expected_quantity
def classify(r):
    if r.actual_side=='MISSING' and r.reason=='insufficient available cash': return ('RISK_REJECTED_ORDER','REPLAY BUG','plain-symbol versus NSE:symbol key mismatch resubmitted retained names; full target request exhausted cash','MATERIAL')
    if r.expected_side=='NONE': return ('EXTRA_ENGINE_ORDER','REPLAY BUG','retained-name membership used plain symbol against NSE-prefixed portfolio keys','MATERIAL')
    if r.actual_side=='MISSING': return ('POSITION_STATE_MISMATCH','POSITION-STATE DIFFERENCE','prior replay divergence meant expected holding/order state no longer existed','MATERIAL')
    if r.expected_side!=r.actual_side: return ('SIDE_MISMATCH','POSITION-STATE DIFFERENCE','diverged engine holdings inverted required transition','MATERIAL')
    return ('QUANTITY_MISMATCH','CASH / SIZING DIFFERENCE','engine equity/cash state and cost-reserve sizing differed after first divergence','MATERIAL')
vals=bad.apply(classify,axis=1,result_type='expand'); vals.columns=['classification','root_cause','root_cause_detail','materiality']; bad=pd.concat([bad,vals],axis=1)
rb=pd.read_csv(ROOT/'reports/sector_strategy/v2/development/v2_rebalances.csv')[['rebalance_id','execution_date','pretrade_equity']]; bad=bad.merge(rb,on='rebalance_id',how='left')
for c in ['research_position_before','paper_position_before','research_position_after','paper_position_after','research_cash_before','paper_cash_before','research_target_weight','paper_target_weight','research_reference_open','paper_reference_open','position_count_before','cash_required']: bad[c]=pd.NA
bad['research_order_present']=bad.expected_side.ne('NONE'); bad['paper_order_present']=bad.actual_side.ne('MISSING'); bad.rename(columns={'expected_side':'research_side','actual_side':'paper_side','expected_quantity':'research_quantity','actual_quantity':'paper_quantity','requested_quantity':'paper_risk_requested_qty','approved_quantity':'paper_risk_approved_qty','approved':'paper_risk_approved','reason':'paper_risk_reason','pretrade_equity':'research_pretrade_equity'},inplace=True); bad['paper_pretrade_equity']=pd.NA
bad.to_csv(OUT/'order_mismatch_attribution.csv',index=False)
rej=risk[~risk.approved].copy(); sample=set(pd.read_json(H/'parity_sample_definition.json').rebalance_id); rej['sample_scope']=rej.rebalance_id.apply(lambda x:'SAMPLED' if x in sample else 'NON_SAMPLED'); rej['contract_assessment']='REPLAY/ADAPTER ARTIFACT'; rej['explanation']=rej.reason.map({'insufficient available cash':'repeated full-target requests for retained names plus no research-style cash clipping','maximum open positions reached':'replay evaluated an entry while divergent holdings already consumed nine slots'}); rej.to_csv(OUT/'risk_rejection_attribution.csv',index=False)
snap=pd.read_csv(H/'historical_engine_snapshots.csv').merge(rb[['rebalance_id','execution_date']],on='rebalance_id'); eq=pd.read_csv(ROOT/'reports/sector_strategy/v2/development/v2_equity_curve.csv')[['date','cash','equity']]; snap=snap.merge(eq,left_on='execution_date',right_on='date'); snap['cash_difference']=snap.engine_cash-snap.cash; snap['equity_difference']=snap.engine_equity-snap.equity; snap['state_classification']=snap.apply(lambda r:'STATE_EXACT' if abs(r.cash_difference)<=.01 and abs(r.equity_difference)<=.01 else 'STATE_DIFFERENT',axis=1); snap.to_csv(OUT/'state_parity_before_rebalance.csv',index=False)
first='SMV2-0019'; rt=pd.read_csv(ROOT/'reports/sector_strategy/v2/development/v2_trades.csv'); eo=pd.read_csv(H/'historical_engine_orders.csv'); trace=pd.concat([rt[rt.rebalance_id.eq(first)].assign(source='RESEARCH_ORDER'),eo[eo.rebalance_id.eq(first)].assign(source='PAPER_ENGINE_ORDER')],ignore_index=True,sort=False); trace.to_csv(OUT/'first_divergence_trace.csv',index=False)
pd.DataFrame([{'audit':'fallback_requests','finding':'Phase13B target replay did not consume a true per-sector frozen fallback artifact; repeated requests were target-name retries, not sequential fallback handling','affected_requests':3656,'classification':'REPLAY BUG'}]).to_csv(OUT/'fallback_request_audit.csv',index=False)
pd.DataFrame([{'reason':'maximum open positions reached','count':int((rej.reason=='maximum open positions reached').sum()),'finding':'divergent holdings consumed cap before one replacement request','classification':'REPLAY/ADAPTER ARTIFACT'}]).to_csv(OUT/'position_cap_audit.csv',index=False)
wt=rt[rt.rebalance_id.isin(sample)&rt.trade_class.eq('WEIGHT_REBALANCING')].copy(); wt['paper_behavior']='not independently implemented in Phase13B replay'; wt['classification']='WEIGHT_TOLERANCE_MISMATCH'; wt.to_csv(OUT/'weight_tolerance_audit.csv',index=False)
(OUT/'sizing_formula_comparison.md').write_text('''# Exact sizing formulas\n\nResearch V2: `pretrade = cash + Σ(q_i × supported_open_i_or_last_mark_i)`; `target_n = max(len(intended), 1)`; `target_value = pretrade / target_n`; retained weight is `q_i × open_i / pretrade`; resize only when `abs(preweight - 1/target_n) >= 0.02`; desired shares are `floor(target_value / (open × (1 + 5/10000) × (1 + 20/10000)))`, then BUY quantity is clipped to available cash.\n\nPhase13B replay: `target_value = paper_equity / len(target)`; new-entry shares are `floor(target_value / (open × 1.0025))`; retained-name detection used `symbol in account.positions` although portfolio keys are `NSE:symbol`; no independent retained-position 2pp resize path was implemented. Risk then rejected the full requested quantity rather than applying the research simulator cash clip.\n''')
(OUT/'execution_sequence_comparison.md').write_text('''# Execution sequence comparison\n\nResearch V2 retries pending exits, executes deselection sells, updates cash, conditionally resizes retained positions outside the 2pp band, then opens signal-frozen entries with cash clipping, and finally marks closes.\n\nPhase13B computed exits and processed them before buys, but retained-position detection used the wrong portfolio key. It consequently treated retained target names as absent, submitted new full-size BUY requests, and relied on RiskManager rejection rather than research-style cash clipping. This is the first structural divergence; generic OrderManager, PaperBroker, and Portfolio sequencing was not the cause.\n''')
summary={'phase13b_evidence_sha256':hashes,'mismatch_total':len(bad),'root_causes':bad.root_cause.value_counts().to_dict(),'classifications':bad.classification.value_counts().to_dict(),'risk_decisions':len(risk),'risk_approved':int(risk.approved.sum()),'risk_rejected':len(rej),'rejection_reasons':rej.reason.value_counts().to_dict(),'first_divergence_rebalance':'SMV2-0019','first_divergence_date':'2020-05-11','phase12b_preregistration_hash':'2e99d105d6a23538dafcaa4d6c17ba71b008c2e30fee63bec2cb50706a6aee2f','phase12c_build':'96e614a5638f221b1c340e4f9201e792b5c01e1394eac682ef7b53480aa0f2fb','post_boundary_performance_inspected':False,'decision':'PARITY ROOT CAUSE IDENTIFIED'}
(OUT/'phase13c_root_cause_summary.json').write_text(json.dumps(summary,indent=2,sort_keys=True)+'\n')
(OUT/'phase13c_root_cause_report.md').write_text(f'''# Phase 13C root-cause attribution\n\nDecision: **PARITY ROOT CAUSE IDENTIFIED**.\n\nAll {len(bad)} mismatches are classified: 53 REPLAY BUG, 27 POSITION-STATE DIFFERENCE, and 21 CASH / SIZING DIFFERENCE. The first rebalance, SMV2-0018, matched; divergence begins at SMV2-0019 on 2020-05-11 when retained holdings were looked up with plain symbols against `NSE:symbol` Portfolio keys. This caused repeated BUY requests for held names, cash exhaustion, and cascading state differences.\n\nRiskManager `RiskLimits(9,100,100)` means maximum 9 open positions, maximum daily loss of 100% of starting capital, and maximum single-position exposure of 100% of current equity. It does not implement V2 target sizing or cash clipping. Of 3,657 rejections, 3,656 were insufficient cash and one was the maximum-position cap. These are replay/adapter artifacts under the submitted request stream.\n\nNo engine or strategy source was modified and no post-boundary performance was inspected.\n''')
print(summary)
