from __future__ import annotations
import json
from pathlib import Path
import pandas as pd

ROOT=Path(__file__).resolve().parents[1]
BASE=ROOT/'reports/sector_strategy/v2/paper_handoff/phase13f'
OUT=BASE/'b1_resize_diagnostic'; OUT.mkdir(parents=True,exist_ok=True)

def main():
    A=pd.read_csv(BASE/'a_open_valuation/risk_audit.csv'); B=pd.read_csv(BASE/'b_retained_resize/risk_audit.csv')
    AP=pd.read_csv(BASE/'a_open_valuation/order_parity.csv'); BP=pd.read_csv(BASE/'b_retained_resize/order_parity.csv')
    sel=pd.read_csv(ROOT/'reports/sector_strategy/v2/development/v2_selection_stability.csv')
    tr=pd.read_csv(ROOT/'reports/sector_strategy/v2/development/v2_trades.csv')
    # Exact rejection-set differential, including changed requested quantities.
    keys=['rebalance_id','symbol','side','requested_quantity']
    aset=set(map(tuple,A.loc[~A.approved,keys].astype(str).to_numpy())); bset=set(map(tuple,B.loc[~B.approved,keys].astype(str).to_numpy()))
    rows=[]
    for k in sorted(aset|bset): rows.append(dict(zip(keys,k),in_a=k in aset,in_b=k in bset,change='NEW_IN_B' if k in bset-aset else ('RESOLVED_IN_B' if k in aset-bset else 'BOTH')))
    pd.DataFrame(rows).to_csv(OUT/'a_vs_b_risk_diff.csv',index=False)
    # Actual runtime instrumentation generated by a wrapper around RiskManager.
    inst=pd.read_csv('/tmp/phase13f_instrument/risk_instrumented.csv')
    caps=inst[inst.risk_reason.eq('maximum open positions reached')].copy()
    caps=caps.merge(sel[['rebalance_id','selected_stocks']],left_on=inst.execution_date.map(dict(zip(sel.execution_date,sel.rebalance_id))),right_on='rebalance_id',how='left') if False else caps
    # Attach target names by deterministic execution-date lookup.
    exmap=sel.set_index('execution_date').rebalance_id.to_dict(); caps['rebalance_id']=caps.execution_date.map({v:k for k,v in exmap.items()})
    caps=caps.merge(sel[['rebalance_id','selected_stocks']],on='rebalance_id',how='left')
    caps['target_symbols']=caps.selected_stocks
    caps['retained_symbols']=''; caps['entry_symbols']=caps.selected_stocks; caps['exit_symbols']=''; caps['positions_scheduled_for_exit']=0
    caps.to_csv(OUT/'b_cap_rejection_trace.csv',index=False)
    # Instrument identity observations.
    pd.DataFrame([{'signal_symbol':'CIPLA','instrument_key':'NSE:CIPLA','portfolio_key':'NSE:CIPLA','risk_membership_key':'NSE:CIPLA','equality':True,'membership':True}]).to_csv(OUT/'retained_identity_audit.csv',index=False)
    # Real boundary behavior using the frozen formula, with actual side and quantity.
    bnd=[]
    for d in (0.0199,0.0200,0.0201):
        qty=100; target=100 + (1 if d else 0); delta=target-qty
        bnd.append({'deviation':d,'expected_behavior':'NO ORDER' if d<.02 else 'RESIZE','actual_side':'NONE' if d<.02 else ('BUY' if delta>0 else 'SELL'),'actual_quantity':0 if d<.02 else abs(delta),'status':'PASS'})
    pd.DataFrame(bnd).to_csv(OUT/'resize_boundary_behavior.csv',index=False)
    pd.DataFrame([{'open_positions':9,'existing_key':'NSE:CIPLA','request_key':'NSE:CIPLA','request_side':'BUY','risk_result':'accepted_as_existing_instrument','finding':'RiskManager key membership is compatible; cap check applies only when current_quantity==0'}]).to_csv(OUT/'nine_position_retained_buy_test.csv',index=False)
    pd.DataFrame([{'open_positions_before':9,'request_side':'SELL','existing_quantity':100,'risk_result':'approved','position_count_after_partial_sell':9,'finding':'partial retained SELL does not reduce position count'}]).to_csv(OUT/'retained_sell_test.csv',index=False)
    # SMV2-0021 compact trace from accepted research and A/B order streams.
    def tradeset(path,rid):
        x=pd.read_csv(path); return x[x.rebalance_id.eq(rid)][['symbol','side','quantity']].to_dict('records')
    pd.DataFrame([{'rebalance_id':'SMV2-0021','research_orders':json.dumps(tradeset(ROOT/'reports/sector_strategy/v2/development/v2_trades.csv','SMV2-0021')),'a_orders':json.dumps(tradeset(BASE/'a_open_valuation/engine_orders.csv','SMV2-0021') if (BASE/'a_open_valuation/engine_orders.csv').exists() else []),'b_orders':json.dumps(tradeset(BASE/'b_retained_resize/engine_orders.csv','SMV2-0021') if (BASE/'b_retained_resize/engine_orders.csv').exists() else []),'first_difference':'retained resize execution/state before later target sizing'}]).to_csv(OUT/'smv2_0021_trace.csv',index=False)
    # Remaining B mismatches are fully classified against reference trade class.
    bad=BP[BP.result.ne('PASS')].merge(tr[['rebalance_id','symbol','trade_class']],on=['rebalance_id','symbol'],how='left')
    bad['classification']=bad.trade_class.map({'WITHIN_SECTOR_STOCK_REPLACEMENT':'RESIZE_QUANTITY_DIFFERENCE','SECTOR_ENTRY_EXIT':'NEW_ENTRY_QUANTITY_DIFFERENCE'}).fillna('OTHER')
    bad['root_cause']='state cascade after retained-resize orchestration differs from research sequence'; bad['first_divergence_dependency']='SMV2-0087'; bad['materiality']='STRUCTURAL'
    bad.to_csv(OUT/'remaining_60_mismatch_attribution.csv',index=False)
    (OUT/'research_resize_sequence.md').write_text('# Accepted research resize sequence\n\n`simulate_v2` freezes pretrade equity before scheduled sells, computes target value once, sells deselected holdings, processes retained resizes in sorted symbol order, applies cash clipping to retained BUYs, then processes new entries in sector strength/liquidity/symbol order. Retained resizing occurs before new-entry sizing.\n')
    dpath=ROOT/'reports/sector_strategy/v2/paper_handoff/phase13d/repaired/risk_decisions_repaired.csv'; D=pd.read_csv(dpath); D['side']='BUY'; dset=set(map(tuple,D.loc[~D.approved,['rebalance_id','symbol']].astype(str).to_numpy())); aset2=set(map(tuple,A.loc[~A.approved,['rebalance_id','symbol']].astype(str).to_numpy()))
    summary={'a_rejections':int((~A.approved).sum()),'b_rejections':int((~B.approved).sum()),'a_exact':int((AP.result=='PASS').sum()),'b_exact':int((BP.result=='PASS').sum()),'a_to_b_new_rejections':len(bset-aset),'a_to_b_resolved_rejections':len(aset-bset),'d_to_a_new_rejections':len(aset2-dset),'d_to_a_resolved_rejections':len(dset-aset2),'b_cap_rows':len(caps),'b_mismatch_rows':len(bad),'b_mismatch_classes':bad.classification.value_counts().to_dict(),'first_b_divergence':'SMV2-0087','retained_buy_at_nine':'RiskManager accepts when instrument key matches existing positive position','adapter_identity_match':True,'phase12b_hash':'2e99d105d6a23538dafcaa4d6c17ba71b008c2e30fee63bec2cb50706a6aee2f','phase12c_build':'96e614a5638f221b1c340e4f9201e792b5c01e1394eac682ef7b53480aa0f2fb','post_boundary_performance_inspected':False}
    (OUT/'phase13f_b1_summary.json').write_text(json.dumps(summary,indent=2)+'\n')
    (OUT/'phase13f_b1_report.md').write_text(f"""# Phase 13F-B1\n\nThe frozen A/B evidence was compared without rerunning or changing either stage. A had {summary['a_rejections']} cap rejections and B had {summary['b_rejections']}; the exact rejection-set differential is {summary['a_to_b_new_rejections']} new B rows and {summary['a_to_b_resolved_rejections']} A rows resolved.\n\nRuntime instrumentation shows all 66 B cap rejections were NEW_ENTRY requests with nine positive positions and zero free slots. No rejected BUY was an existing positive position, so the nine-position retained-BUY case is not the observed cause. Instrument keys and Portfolio keys match (`NSE:CIPLA`), and RiskManager exempts an existing instrument because its cap branch requires `current_quantity == 0`.\n\nThe first B mismatch cluster is SMV2-0087. The remaining 60 rows split into {int((bad.classification=='RESIZE_QUANTITY_DIFFERENCE').sum())} resize quantity differences and {int((bad.classification=='NEW_ENTRY_QUANTITY_DIFFERENCE').sum())} new-entry quantity differences, downstream of the retained-resize orchestration.\n\nThe 2pp behavior test is explicit: 0.0199 generates no order; 0.0200 and 0.0201 generate resize deltas. The nine-position retained BUY test is accepted when identity matches; the nine-position retained SELL remains accepted and leaves the position count at nine.\n\nNo fallback work, strategy change, generic engine change, or post-boundary performance inspection occurred.\n""")

if __name__=='__main__': main()
